# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_NUC980) += \
        nuc980-dev-v1.0.dtb \
        nuc980-iot-v1.0.dtb \
        nuc980-iot-g2-v1.0.dtb \
        nuc980-iot-g2d-v1.0.dtb \
        nuc980-lorag.dtb \
        nuc980-eth2uart.dtb \
        nuc980-chili.dtb \
        nuc980-usb8p-v1.0.dtb
dtb-$(CONFIG_ARCH_NPCM7XX) += \
	nuvoton-npcm730-gsj.dtb \
	nuvoton-npcm730-gbs.dtb \
	nuvoton-npcm730-kudo.dtb \
	nuvoton-npcm750-evb.dtb \
	nuvoton-npcm750-runbmc-olympus.dtb
dtb-$(CONFIG_ARCH_WPCM450) += \
	nuvoton-wpcm450-supermicro-x9sci-ln4f.dtb
