#
# Makefile for the linux kernel.
#

# Object file lists.
obj-y                           := cpu.o mfp.o pm.o suspend.o time.o irq.o mach-nuc980.o dev.o

obj-$(CONFIG_USE_OF)  		+= dt-nuc980-dev-v1.0.o
